import type { AgentRoleDict } from "./AgentRoleSection";

export const AGENT_ROLE_DICT_EN: AgentRoleDict = {
  badge: "Join the Future of Travel",
  heroTitle: "Become a Zeniva Agent",
  heroSub: "Join the future of travel. Earn 70% commission. Work from anywhere.",
  heroCta: "Apply Now",
  heroPricingNote: "Setup fee: $299 one-time · $97/month subscription",
  benefitsTitle: "Why Join Zeniva?",
  benefitsSub: "Everything you need to succeed as a travel agent, powered by AI",
  benefits: [
    { icon: "💰", title: "70% Commission", desc: "Keep 70% of net profit on every booking. No hidden fees, transparent payouts." },
    { icon: "🤖", title: "AI Assistant Lina", desc: "Your personal AI agent handles clients 24/7. Quote generation, booking management, customer support." },
    { icon: "💳", title: "ZeniPay Account", desc: "Receive payments instantly. Professional invoicing and payment processing included." },
    { icon: "📱", title: "Full Tech Setup", desc: "Phone number via Tillo, professional email, n8n automation workflows — all configured for you." },
    { icon: "🌍", title: "200+ Destinations", desc: "Access our global network of hotels, yachts, villas, cruises and exclusive packages." },
    { icon: "🎓", title: "No Experience Required", desc: "Complete training included. We teach you everything from booking to client management." },
  ],
  pricingTitle: "Transparent Pricing",
  pricingSub: "Simple, straightforward. No surprises.",
  setupOnce: "One-time",
  setupTitle: "Setup Fee",
  setupItems: [
    "Complete account configuration",
    "Phone number via Tillo",
    "Professional email setup",
    "Lina AI personal assistant",
    "n8n automation workflows",
    "ZeniPay merchant account",
  ],
  monthlyRequired: "REQUIRED",
  monthlyTitle: "Per Month",
  monthlyItems: [
    "All tools included",
    "Lina AI unlimited access",
    "ZeniPay dashboard",
    "Priority support",
    "Training & resources",
    "Software updates",
  ],
  referralTitle: "Refer & Earn",
  referralSub: "Grow your network and get rewarded",
  referrals: [
    { tier: "1️⃣", title: "Recruit 1 Agent", desc: "Get <strong>1 month free</strong>" },
    { tier: "2️⃣", title: "Recruit 2 Agents", desc: "Get your <strong>$299 setup fee</strong> fully reimbursed" },
    { tier: "3️⃣", title: "Recruit 3+ Agents", desc: "Become a <strong>Zeniva Ambassador</strong> with bonus commissions" },
  ],
  howTitle: "How It Works",
  howSub: "Four simple steps to get started",
  steps: [
    { step: "1", title: "Apply & Pay Setup Fee", desc: "Fill out the application and pay the $299 one-time setup fee to get started." },
    { step: "2", title: "We Configure Everything", desc: "Our team sets up your phone, email, Lina AI, ZeniPay account within 24 hours." },
    { step: "3", title: "Receive Your Credentials", desc: "Get your login, phone number, email and full access to Lina AI assistant." },
    { step: "4", title: "Start Earning 70%", desc: "Begin booking for clients and keep 70% commission on every transaction." },
  ],
  exampleTitle: "Commission Example",
  exampleSub: "See how much you can earn per booking",
  exampleBookingValue: "Booking value",
  exampleSupplierCost: "Supplier cost",
  exampleNetProfit: "Net profit",
  exampleCommission: "Your 70% commission",
  exampleNumbers: { booking: "$7,677", cost: "$5,078", net: "$2,599", commission: "$1,819" },
  exampleHint: "<strong>That's $1,819 per booking</strong> — imagine 5–10 bookings per month 💰",
  finalTitle: "Ready to Start?",
  finalSub: "Join hundreds of agents earning 70% commission with full tech setup and AI support",
  finalCta: "Become an Agent — $299 Setup",
  finalContact: "Questions? Email us at",
  finalContactEmail: "agents@zeniva.ca",
};

export const AGENT_ROLE_DICT_FR: AgentRoleDict = {
  badge: "Rejoins le futur du voyage",
  heroTitle: "Deviens agent Zeniva",
  heroSub: "Rejoins le futur du voyage. Gagne 70% de commission. Travaille de partout.",
  heroCta: "Postuler",
  heroPricingNote: "Frais d'installation : 299 $ une fois · 97 $/mois d'abonnement",
  benefitsTitle: "Pourquoi rejoindre Zeniva ?",
  benefitsSub: "Tout ce qu'il te faut pour réussir comme agent de voyage, propulsé par l'IA",
  benefits: [
    { icon: "💰", title: "70% de commission", desc: "Garde 70% du profit net sur chaque réservation. Aucun frais caché, paiements transparents." },
    { icon: "🤖", title: "Lina, ton assistante IA", desc: "Ton agent IA personnel s'occupe de tes clients 24/7. Devis, gestion des réservations, support." },
    { icon: "💳", title: "Compte ZeniPay", desc: "Reçois tes paiements instantanément. Facturation pro et traitement des paiements inclus." },
    { icon: "📱", title: "Stack technique complète", desc: "Numéro de téléphone via Tillo, email pro, workflows n8n — tout est configuré pour toi." },
    { icon: "🌍", title: "200+ destinations", desc: "Accède à notre réseau mondial d'hôtels, yachts, villas, croisières et forfaits exclusifs." },
    { icon: "🎓", title: "Aucune expérience requise", desc: "Formation complète incluse. On t'apprend tout, de la réservation à la gestion client." },
  ],
  pricingTitle: "Tarification transparente",
  pricingSub: "Simple, clair. Sans surprise.",
  setupOnce: "Une seule fois",
  setupTitle: "Frais d'installation",
  setupItems: [
    "Configuration complète du compte",
    "Numéro de téléphone via Tillo",
    "Email professionnel",
    "Assistante IA Lina",
    "Workflows n8n",
    "Compte marchand ZeniPay",
  ],
  monthlyRequired: "REQUIS",
  monthlyTitle: "Par mois",
  monthlyItems: [
    "Tous les outils inclus",
    "Accès illimité à Lina AI",
    "Tableau de bord ZeniPay",
    "Support prioritaire",
    "Formation & ressources",
    "Mises à jour logicielles",
  ],
  referralTitle: "Parraine & gagne",
  referralSub: "Fais grandir ton réseau et reçois des récompenses",
  referrals: [
    { tier: "1️⃣", title: "Parraine 1 agent", desc: "Reçois <strong>1 mois offert</strong>" },
    { tier: "2️⃣", title: "Parraine 2 agents", desc: "Tes <strong>299 $ d'installation</strong> sont entièrement remboursés" },
    { tier: "3️⃣", title: "Parraine 3+ agents", desc: "Deviens <strong>Ambassadeur Zeniva</strong> avec des commissions bonus" },
  ],
  howTitle: "Comment ça marche",
  howSub: "Quatre étapes simples pour démarrer",
  steps: [
    { step: "1", title: "Postule & paye l'installation", desc: "Remplis ta candidature et règle les 299 $ d'installation pour démarrer." },
    { step: "2", title: "On configure tout", desc: "Notre équipe configure ton téléphone, email, Lina AI et ZeniPay sous 24 heures." },
    { step: "3", title: "Reçois tes accès", desc: "Identifiants, numéro de téléphone, email et accès complet à Lina AI." },
    { step: "4", title: "Commence à gagner 70%", desc: "Réserve pour tes clients et garde 70% de commission sur chaque transaction." },
  ],
  exampleTitle: "Exemple de commission",
  exampleSub: "Vois ce que tu peux gagner par réservation",
  exampleBookingValue: "Valeur de la réservation",
  exampleSupplierCost: "Coût fournisseur",
  exampleNetProfit: "Profit net",
  exampleCommission: "Ta commission de 70%",
  exampleNumbers: { booking: "7 677 $", cost: "5 078 $", net: "2 599 $", commission: "1 819 $" },
  exampleHint: "<strong>1 819 $ par réservation</strong> — imagine 5 à 10 réservations par mois 💰",
  finalTitle: "Prêt à démarrer ?",
  finalSub: "Rejoins des centaines d'agents qui gagnent 70% de commission avec un setup tech complet et le support IA",
  finalCta: "Devenir agent — 299 $ d'installation",
  finalContact: "Des questions ? Écris-nous à",
  finalContactEmail: "agents@zeniva.ca",
};
